version: "3.8"

services:
  frontend:
    build:
      context: ./oriobook-frontend
    image: ngductuan/oriobook-fe:${IMAGE_TAG}
    container_name: orio-fe
    ports:
      - "5001:80"
    env_file:
      - .env

  backend:
    build:
      context: ./oriobook-backend
    image: ngductuan/oriobook-be:${IMAGE_TAG}
    container_name: orio-be
    ports:
      - "5002:8080"
    env_file:
      - backend.env
