version: "3.8"

services:
  frontend:
    build:
      context: ./oriobook-frontend
    image: ngductuan/oriobook-fe:${IMAGE_TAG}
    container_name: orio-fe
    env_file:
      - ./oriobook-frontend/.env
    ports:
      - "5001:80"

  backend:
    build:
      context: ./oriobook-backend
    image: ngductuan/oriobook-be:${IMAGE_TAG}
    container_name: orio-be
    env_file:
      - ./oriobook-backend/.env
    ports:
      - "5002:8080"
    volumes:
      - /logs/oriobook:/logs
