version: '3.8'

services:
  kafka:
    image: bitnami/kafka:3.5
    container_name: kafka_container
    env_file:
      - kafka.env
    environment:
      KAFKA_ENABLE_KRAFT: "yes"
      KAFKA_CFG_NODE_ID: "1"
      KAFKA_CFG_PROCESS_ROLES: "controller,broker"
      KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093"
      KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://${KAFKA_HOST:-localhost}:9092"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "1@kafka_container:9093"
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_HEAP_OPTS: "-Xmx512M -Xms256M"
      # Tạo Cluster ID một cách động bằng lệnh khởi tạo
      KAFKA_KRAFT_CLUSTER_ID: "${KAFKA_KRAFT_CLUSTER_ID:-}"
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
    ports:
      - "9092:9092" # using to connect to [client:other services]
      - "9093:9093" # using to connect to kafka brokers
    volumes:
      - ./kafka/broker1:/bitnami/kafka:rw
    networks:
      - kafka-net

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka_ui_container
    environment:
      KAFKA_CLUSTERS_0_NAME: "local"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka_container:9092"
    ports:
      - "9091:8080"
    depends_on:
      - kafka
    networks:
      - kafka-net

  connect:
    image: quay.io/debezium/connect:2.7.0.Final
    container_name: connect_container
    ports:
      - "8083:8083"
    environment:
      BOOTSTRAP_SERVERS: "kafka_container:9092"
      GROUP_ID: "1"
      CONFIG_STORAGE_TOPIC: "my_connect_configs"
      OFFSET_STORAGE_TOPIC: "my_connect_offsets"
      STATUS_STORAGE_TOPIC: "my_connect_statuses"
    depends_on:
      - kafka
    volumes:
      - ./oriobook-connector.jar:/kafka/connect/oriobook-connector.jar
    networks:
      - kafka-net

networks:
  kafka-net:
    driver: bridge